---
Name: mainsite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension
Block:
  extensions:
    - GenericBlockExtension
  DisabledBlocks:
    - Block
    - DualColumnBlock
    - TriColumnBlock
DataList:
  extensions:
    - DataListExt
MenuSet:
  default_sets:
    - "Footer"
SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false
GoogleAPIs:
  Map: AIzaSyCja9gWSRzZ_XOmMaNLGjpGfpUGlwHXe48
i18n:
  all_locales:
    zh_Hans: Chinese (Simplified)
    zh_Hant: Chinese (Traditional)
  common_locales:
    th_TH:
      name: Thai (Thailand)
      native: ไทย
    zh_Hans:
      name: Chinese (Simplified)
      native: 简体中文
    zh_Hant:
      name: Chinese (Traditional)
      native: 繁體中文
    ko_KR:
      name: Korean (Korea)
      native: 한국어
