---
Name: 'silverstripejsmanager'
After: 'framework/*','cms/*', 'siteconfig/*'
---
#SiteConfig:
#  extensions:
#    - SiteJSExtension
SiteJsConfig:
  extensions:
    - Versioned("Stage","Live")
#Controller:
#  extensions:
#    - SiteJSControllerExtension
#SiteTree:
#  extensions:
#    - SiteJSPageDecorator